config/routes.rb
Myapp3::Application.routes.draw do

  get "menu/index"
  get "spot_regist/index"

  resources :addresses
  resources :users 
  resources :menu
  resources :spots

end

app/models/address.rb
class Address < ActiveRecord::Base
  attr_accessible :email, :name
end

app/models/spots.rb
class Spots < ActiveRecord::Base
  attr_accessible :spotname
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :account, :password_digest, :password, :password_confirmation
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @addresses }
    end
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
    @address = Address.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/new
  # GET /addresses/new.json
  def new
    @address = Address.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @address }
    end
  end

  # GET /addresses/1/edit
  def edit
    @address = Address.find(params[:id])
  end

  # POST /addresses
  # POST /addresses.json
  def create
    @address = Address.new(params[:address])

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render json: @address, status: :created, location: @address }
      else
        format.html { render action: "new" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /addresses/1
  # PUT /addresses/1.json
  def update
    @address = Address.find(params[:id])

    respond_to do |format|
      if @address.update_attributes(params[:address])
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address = Address.find(params[:id])
    @address.destroy

    respond_to do |format|
      format.html { redirect_to addresses_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
  end
end

app/controllers/spot_regist_controller.rb
class SpotRegistController < ApplicationController
  def index
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  def index
    render 'index'    
  end

  def create
   #重複なしでスポット名だけをとってくる
   @spots = Spots.select('spotname').where('spotname like ?', "%"+params[:spot_str]+"%").uniq

   #重複ありでスポットIDも一緒にとってくる
   #@spots = Spots.where('spotname like ?', "%"+params[:spot_str]+"%")

   respond_to do |format|
     format.html
     format.json { render json: @spots }
   end
  end

  def show

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    render 'new'
  end
  
  def create
    user = User.find_by_account params[:account]
    if user && user.authenticate(params[:pass])
      session[:user_id] = user.id
      render 'login_success'
    else
      render 'login_failure'
    end
  end
  
  def destroy
    session[:user_id] = nil
    render "new"
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/spot_regist_helper.rb
module SpotRegistHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/addresses/_form.html.erb
<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/addresses/edit.html.erb
<h1>Editing address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<h1>Listing addresses</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @addresses.each do |address| %>
  <tr>
    <td><%= address.name %></td>
    <td><%= address.email %></td>
    <td><%= link_to 'Show', address %></td>
    <td><%= link_to 'Edit', edit_address_path(address) %></td>
    <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<h1>New address</h1>

<%= render 'form' %>

<%= link_to 'Back', addresses_path %>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @address.name %>
</p>

<p>
  <b>Email:</b>
  <%= @address.email %>
</p>


<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Title3</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/menu/index.html.erb
<h1>メニュー</h1>
<p>選択してください</p>
<%= link_to 'SpotRegist', :controller => 'spot_regist', :action => 'index' %>
<%= link_to 'SpotSearch', :controller => 'spots', :action => 'index' %>

app/views/spot_regist/index.html.erb
<h1>Spot登録画面</h1>
<p>作成中</p>

app/views/spots/create.html.erb
<h1>検索結果</h1>

<table>
  <tr>
    <th>spotname</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @spots.each do |spot| %>
  <tr>
    <td><%= spot.spotname %></td>
    <td><%= link_to 'メッセージを送ってみる', '/spots/show' %></td>
  </tr>
<% end %>
</table>

<br />

app/views/spots/index.html.erb
<h1>検索</h1>

<%= form_tag spots_path do %>
  <table>
    <tr>
      <td><%= label_tag "スポット検索" %></td>
      <td><%= text_field_tag :spot_str %></td>
    </tr> 

    <tr>
      <td><%= submit_tag "検索" %></td>
    </tr>
  </table>
<% end %>

app/views/users/login_failure.html.erb
<h1>ログイン失敗</h1>
<p>
アカウント名又はパスワードが間違っているため、<br>
ログイン出来ませんでした。
</p>

<%= link_to "もう一度ログインする", users_path %>

app/views/users/login_success.html.erb
<h1>ログイン成功</h1>
<p>
ログイン成功しました。
</p>
<%= link_to 'メニューへ遷移', :controller => 'menu', :action => 'index' %>
<%= link_to 'ログアウトする', user_path(session[:user_id]), :confirm => 'ログアウトしますか？', :method => :delete %>

app/views/users/new.html.erb
<h1>ログイン画面</h1>

<%= form_tag users_path do %>
<table id="login_form">
    <tr>
    <td><%= label_tag :account, 'アカウント名' %></td>
    <td><%= text_field_tag :account, params[:account] %></td>
</tr>

<tr>
    <td><%= label_tag :pass, 'パスワード' %></td>
    <td><%= password_field_tag :pass, params[:pass] %></td>
</tr>

<tr>
    <td><%= submit_tag "ログイン" %></td>
</tr>
</table>

<% end %>